version: '3.9'

services:
  mongodb:
    image: mongo
    ports:
      - 27017:${MONGO_PORT:-27017}
    volumes:
      - mongodbdata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME="${MONGO_ROOT_USERNAME:-root}"
      - MONGO_INITDB_ROOT_PASSWORD="${MONGO_ROOT_PASSWORD:-secret}"

volumes:
  mongodbdata:
